<?php
/*
// The MIT License (MIT)
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
SOFTWARE.
*/
?>
<?php
/*
FILE : DELETE_SEARCH.PHP
PURPOSE :  DELETE SAVED SEARCHES VIA AJAX
ACCESS TYPE : DIRECT
*/
include_once(dirname(__FILE__)."/../../config/globals.php");
$deleted=0;

// SET VALUES
if($_REQUEST['sTxt']!=''){
	$qry="Delete FROM reports_searches WHERE report_name='".trim(addslashes($_REQUEST['sTxt']))."'";
	$rs=imw_query($qry);
	if($rs){
		$deleted=1;
	}
	$deleted=1;
}
//--------------
echo $deleted;
?>
