#!/bin/bash
#Name : SFTP sender Service
#Desc : Starts/stop SFTP HL7 sender services for iMW on reboot
SCRIPT=$(readlink -f "$0")
SCRIPTPATH=$(dirname "$SCRIPT")
DAEMON="/usr/bin/php"
DAEMON_OPTS="$SCRIPTPATH/write_outbound_service.php"
NAME="HL7 SFTP Sender Service"
DESC="HL7 SFTP Sender Service"

usage() {
  echo -n "Usage: $0 [arg1] [arg2]

 where:
        "arg1"          start|stop|restart|status
        "arg2"          Name of R8 site, for which HL7 is configured.
"
}

if [ ! -d "$SCRIPTPATH/../../config/$2" ] || [ "$2" = '' ]; then
	if [ "$2" = '' ]; then
		echo -e "Please provide a practice name"
		usage
	else
		echo "$2 Practice does not exists"
	fi
	
	exit
fi

getPid() {
	PID=`ps -eaf |egrep "$DAEMON_OPTS" |grep $2 |grep -v grep |awk '{print $2}'`
	echo "$PID"
}


start() {
if [[ "" != "$( getPid $1 $2)" ]];
then
    echo "$2 sender is already running with PID $( getPid $1 $2)"
else
    echo -e "${NAME}: Starting..."
    `nohup $DAEMON $DAEMON_OPTS "$2" > /dev/null 2>&1 &`
    sleep 1
	if [[ "" != "$( getPid $1 $2)" ]]; then
	        echo -e "Sender Started"
	else
		echo -e "Unable to start sender"
	fi
fi
}

stop() {
if [[ "" != "$( getPid $1 $2)" ]]; then
    echo -e "${NAME}: Stopping..."
    kill -9 $( getPid $1 $2)
    sleep 1
    
	if [[ "" ==  "$( getPid $1 $2)" ]]; then
	        echo -e "Sender Stopped"
	else
		echo -e "Unable to stop sender"
	fi
else
        echo "Sender not running"
fi
}

status() {
if [[ "" != "$( getPid $1 $2)" ]]; then
	echo "$2 sender is running with PID $( getPid $1 $2)"
else
        echo "Sender not running"
fi
}

case "$1" in
start)
	start $1 $2
        ;;
stop)
        stop $1 $2
        ;;
status)
        status $1 $2
        ;;
restart)
        stop $1 $2
	sleep 1
        start $1 $2
        ;;
*)
	usage
        exit 1
        ;;
esac
exit 0
